// Step 10: Minimal integration module for passto-planner.
// Reads review outputs, aggregates findings into
// accepted/rejected/unresolved categories, and writes
// passto-integration-notes.md.

import { readTextFile, writeTextFile } from "./file-io.ts";
import * as path from "node:path";

// ── Public Types ────────────────────────────────────────────────────

export interface IntegrationConfig {
  runId: string;
  planningDir: string;
  goal: string;
  target?: string;
}

export interface IntegrationFinding {
  text: string;
  source: string;
  category: "accepted" | "rejected" | "unresolved";
  rationale: string;
}

export interface IntegrationOutput {
  filePath: string;
  findings: IntegrationFinding[];
  accepted: number;
  rejected: number;
  unresolved: number;
  summary: string;
}

// ── Review File Definitions ─────────────────────────────────────────

const REVIEW_FILES = [
  { id: "gpt-5.4", name: "GPT-5.4", file: "reviews/gpt-5.4-review.md" },
  { id: "claude-opus-4-6", name: "Claude Opus 4.6", file: "reviews/claude-opus-4-6-review.md" },
];

// ── Finding Extraction ──────────────────────────────────────────────

/**
 * Extract structured findings from review content.
 * Parses known section headers and extracts actionable items.
 */
function extractFindings(
  reviewerName: string,
  content: string,
): string[] {
  const findings: string[] = [];
  const sections = [
    "Input Chain Issues",
    "Runtime Node Issues",
    "Artifact Issues",
    "Constraint Issues",
    "Suggested Fixes",
  ];

  for (const section of sections) {
    const headerIdx = content.indexOf(`### ${section}`);
    if (headerIdx === -1) continue;

    // Find the next section header or end of content
    let endIdx = content.length;
    for (const nextSection of sections) {
      if (nextSection === section) continue;
      const nextIdx = content.indexOf(`### ${nextSection}`, headerIdx + 1);
      if (nextIdx !== -1 && nextIdx < endIdx) endIdx = nextIdx;
    }
    // Also check for ## section headers
    const majorHeaderIdx = content.indexOf("\n## ", headerIdx + 1);
    if (majorHeaderIdx !== -1 && majorHeaderIdx < endIdx) endIdx = majorHeaderIdx;

    const sectionContent = content.substring(headerIdx, endIdx).trim();
    // Extract bullet points
    const bulletRegex = /^- (.+)$/gm;
    let match;
    while ((match = bulletRegex.exec(sectionContent)) !== null) {
      findings.push(`[${section}] ${match[1].trim()}`);
    }
  }

  return findings;
}

// ── Finding Classification ──────────────────────────────────────────

/**
 * Classify findings into accepted/rejected/unresolved.
 * In this minimal implementation, all actionable findings are
 * marked as "accepted" or "unresolved" based on their nature.
 */
function classifyFindings(
  reviewerName: string,
  rawFindings: string[],
): IntegrationFinding[] {
  return rawFindings.map((text) => {
    // Determine category based on content keywords
    const isSuggested = text.includes("[Suggested Fixes]");
    const isIssue = text.includes("[Input Chain Issues]") ||
                    text.includes("[Runtime Node Issues]") ||
                    text.includes("[Artifact Issues]") ||
                    text.includes("[Constraint Issues]");

    let category: "accepted" | "rejected" | "unresolved";
    let rationale: string;

    if (isSuggested) {
      category = "accepted";
      rationale = `Actionable suggestion from ${reviewerName}; incorporated into planning notes.`;
    } else if (isIssue) {
      // Issues are accepted for tracking, may need further resolution
      if (text.toLowerCase().includes("verify") || text.toLowerCase().includes("confirm") ||
          text.toLowerCase().includes("pending") || text.toLowerCase().includes("needs")) {
        category = "unresolved";
        rationale = `Issue from ${reviewerName} requires further verification or user input.`;
      } else {
        category = "accepted";
        rationale = `Issue from ${reviewerName} acknowledged and noted for follow-up.`;
      }
    } else {
      category = "unresolved";
      rationale = `Unclassified finding from ${reviewerName}; pending manual review.`;
    }

    return { text, source: reviewerName, category, rationale };
  });
}

// ── Output Generation ──────────────────────────────────────────────

function buildIntegrationMarkdown(
  config: IntegrationConfig,
  findings: IntegrationFinding[],
): string {
  const lines: string[] = [];

  lines.push("# Passto Integration Notes");
  lines.push("");
  lines.push(`Generated by passto-planner Step 10 · Run: ${config.runId}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Overview
  lines.push("## Overview");
  lines.push("");
  lines.push(`- Goal: ${config.goal}`);
  if (config.target) lines.push(`- Target: ${config.target}`);
  lines.push(`- Reviews processed: ${REVIEW_FILES.length}`);
  lines.push(`- Total findings: ${findings.length}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Accepted
  const accepted = findings.filter((f) => f.category === "accepted");
  lines.push("## Accepted Findings");
  lines.push("");
  if (accepted.length) {
    for (const f of accepted) {
      lines.push(`- ${f.text}`);
      lines.push(`  - Source: ${f.source}`);
      lines.push(`  - Rationale: ${f.rationale}`);
      lines.push("");
    }
  } else {
    lines.push("*No accepted findings.*");
    lines.push("");
  }

  lines.push("---");
  lines.push("");

  // Rejected
  const rejected = findings.filter((f) => f.category === "rejected");
  lines.push("## Rejected Findings");
  lines.push("");
  if (rejected.length) {
    for (const f of rejected) {
      lines.push(`- ${f.text}`);
      lines.push(`  - Source: ${f.source}`);
      lines.push(`  - Rationale: ${f.rationale}`);
      lines.push("");
    }
  } else {
    lines.push("*No rejected findings.*");
    lines.push("");
  }

  lines.push("---");
  lines.push("");

  // Unresolved
  const unresolved = findings.filter((f) => f.category === "unresolved");
  lines.push("## Unresolved Findings");
  lines.push("");
  if (unresolved.length) {
    for (const f of unresolved) {
      lines.push(`- ${f.text}`);
      lines.push(`  - Source: ${f.source}`);
      lines.push(`  - Rationale: ${f.rationale}`);
      lines.push("");
    }
  } else {
    lines.push("*No unresolved findings.*");
    lines.push("");
  }

  lines.push("---");
  lines.push("");

  // Next Steps
  lines.push("## Next Steps");
  lines.push("");
  if (unresolved.length) {
    lines.push(`- ${unresolved.length} unresolved finding(s) require attention before proceeding.`);
  }
  lines.push("- Proceed to user review gate (Step 11) after resolving outstanding items.");
  lines.push("- Re-run review cycle if significant plan changes are made.");
  lines.push("");

  return lines.join("\n");
}

// ── Main Entry ─────────────────────────────────────────────────────

export async function runStep10Integration(config: IntegrationConfig): Promise<IntegrationOutput> {
  // Read all review files
  const allFindings: IntegrationFinding[] = [];

  for (const reviewDef of REVIEW_FILES) {
    const reviewPath = path.join(config.planningDir, reviewDef.file);
    const content = readTextFile(reviewPath);

    if (!content) {
      // Review file doesn't exist — note it but don't fail
      allFindings.push({
        text: `Review file ${reviewDef.file} not found; review step may not have been executed.`,
        source: reviewDef.name,
        category: "unresolved",
        rationale: `Missing review output; integration cannot process absent review.`,
      });
      continue;
    }

    const rawFindings = extractFindings(reviewDef.name, content);
    const classified = classifyFindings(reviewDef.name, rawFindings);
    allFindings.push(...classified);
  }

  const accepted = allFindings.filter((f) => f.category === "accepted").length;
  const rejected = allFindings.filter((f) => f.category === "rejected").length;
  const unresolved = allFindings.filter((f) => f.category === "unresolved").length;

  // Build and write integration notes
  const markdown = buildIntegrationMarkdown(config, allFindings);
  const filePath = path.join(config.planningDir, "passto-integration-notes.md");
  writeTextFile(filePath, markdown);

  return {
    filePath,
    findings: allFindings,
    accepted,
    rejected,
    unresolved,
    summary: `Integration complete: ${accepted} accepted, ${rejected} rejected, ${unresolved} unresolved from ${REVIEW_FILES.length} review(s).`,
  };
}
