// Step 4: Minimal research module for passto-planner.
// Constructs research tasks, executes them via nested execution,
// aggregates results, and writes passto-research.md.

import type {
  NestedTaskSpec,
  NestedTaskResult,
  NestedExecutionResult,
} from "./nested-execution.ts";
import { runNestedPlannerExecution } from "./nested-execution.ts";
import { writeTextFile } from "./file-io.ts";
import * as path from "node:path";

// ── Public Types ────────────────────────────────────────────────────

export interface ResearchConfig {
  runId: string;
  planningDir: string;
  goal: string;
  target?: string;
  cwd?: string;
}

export interface ResearchOutput {
  researchFilePath: string;
  taskCount: number;
  succeeded: number;
  failed: number;
  summary: string;
}

// ── Task Construction ──────────────────────────────────────────────

function buildResearchTasks(config: ResearchConfig): NestedTaskSpec[] {
  const tasks: NestedTaskSpec[] = [];

  // Task 1: Environment / Dependency / External Facts research.
  tasks.push({
    id: "research-env-01",
    kind: "research-environment",
    title: "Environment / Dependency / External Facts Research",
    prompt:
      "Research the environment constraints, dependency requirements, " +
      "and external facts relevant to the planning goal. " +
      "Identify version compatibilities, runtime requirements, " +
      "and any external service or API dependencies. " +
      "Do NOT write any files. Return findings only.",
    metadata: {
      target: config.target ?? config.goal,
      cwd: config.cwd,
    },
  });

  // Task 2: Web topic research — uses goal-derived topic.
  const webTopic = config.target ?? config.goal;
  tasks.push({
    id: "research-web-01",
    kind: "research-web",
    title: `Web Research: ${webTopic}`,
    prompt:
      `Research best practices, patterns, and current state for: ${webTopic}. ` +
      "Identify relevant frameworks, libraries, architectural patterns, " +
      "and industry standards. " +
      "Do NOT write any files. Return findings only.",
    metadata: {
      topic: webTopic,
      target: config.target ?? config.goal,
    },
  });

  return tasks;
}

// ── Output Aggregation ─────────────────────────────────────────────

function buildResearchMarkdown(config: ResearchConfig, executionResult: NestedExecutionResult): string {
  const lines: string[] = [];

  lines.push("# Passto Research");
  lines.push("");
  lines.push(`Generated by passto-planner Step 4 · Run: ${config.runId}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Research Scope
  lines.push("## Research Scope");
  lines.push("");
  lines.push(`- Goal: ${config.goal}`);
  if (config.target) lines.push(`- Target: ${config.target}`);
  if (config.cwd) lines.push(`- Working Directory: ${config.cwd}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Environment / Dependency / External Facts
  lines.push("## Environment / Dependency / External Facts");
  lines.push("");
  const envTasks = (executionResult.taskResults ?? []).filter(
    (r) => r.kind === "research-environment",
  );
  if (envTasks.length) {
    for (const task of envTasks) {
      lines.push(task.outputText);
      lines.push("");
    }
  } else {
    lines.push("*No environment research results available.*");
    lines.push("");
  }

  lines.push("---");
  lines.push("");

  // Web Topic Research
  lines.push("## Web Topic Research");
  lines.push("");
  const webTasks = (executionResult.taskResults ?? []).filter(
    (r) => r.kind === "research-web",
  );
  if (webTasks.length) {
    for (const task of webTasks) {
      lines.push(task.outputText);
      lines.push("");
    }
  } else {
    lines.push("*No web research results available.*");
    lines.push("");
  }

  lines.push("---");
  lines.push("");

  // Open Questions
  lines.push("## Open Questions");
  lines.push("");
  const failedTasks = (executionResult.taskResults ?? []).filter(
    (r) => r.status === "failed",
  );
  if (failedTasks.length) {
    for (const task of failedTasks) {
      lines.push(`- **${task.summary}**: ${task.failureReason ?? "unknown error"}`);
    }
  }
  lines.push("- Environment constraints pending user confirmation.");
  lines.push("- Web research findings should be validated against project scope.");
  lines.push("- Codebase research to be expanded in later phases.");
  lines.push("");

  return lines.join("\n");
}

// ── Main Entry ─────────────────────────────────────────────────────

export async function runStep4Research(config: ResearchConfig): Promise<ResearchOutput> {
  const tasks = buildResearchTasks(config);

  const executionResult = await runNestedPlannerExecution({
    runId: config.runId,
    goal: config.goal,
    phase: "research",
    strategy: "subagent",
    tasks,
    maxConcurrency: 1,
  });

  const taskResults = executionResult.taskResults ?? [];
  const succeeded = taskResults.filter((r) => r.status === "success").length;
  const failed = taskResults.filter((r) => r.status === "failed").length;

  // Build and write passto-research.md
  const markdown = buildResearchMarkdown(config, executionResult);
  const researchFilePath = path.join(config.planningDir, "passto-research.md");
  writeTextFile(researchFilePath, markdown);

  return {
    researchFilePath,
    taskCount: tasks.length,
    succeeded,
    failed,
    summary: executionResult.summary,
  };
}
