// Step 11: Minimal review gate module for passto-planner.
// Checks existing planning artifacts, determines review-gate readiness,
// and produces a review-gate-ready summary artifact for Step 12 consumption.

import { readTextFile, writeTextFile } from "./file-io.ts";
import * as path from "node:path";

// ── Public Types ────────────────────────────────────────────────────

export interface ReviewGateConfig {
  runId: string;
  planningDir: string;
  goal: string;
  target?: string;
}

export interface ReviewGateArtifact {
  availableArtifacts: ArtifactStatus[];
  unresolvedItems: string[];
  reviewGateReady: boolean;
  summary: string;
  filePath: string;
}

export interface ArtifactStatus {
  name: string;
  path: string;
  exists: boolean;
  size: number | null;
}

// ── Artifact Definitions ────────────────────────────────────────────

const ARTIFACT_SCAN_LIST = [
  { name: "analysis.md", file: "analysis.md" },
  { name: "passto-research.md", file: "passto-research.md" },
  { name: "passto-spec.md", file: "passto-spec.md" },
  { name: "pre-plan.md", file: "pre-plan.md" },
  { name: "passto-integration-notes.md", file: "passto-integration-notes.md" },
  { name: "gpt-5.4 review", file: "reviews/gpt-5.4-review.md" },
  { name: "claude-opus-4-6 review", file: "reviews/claude-opus-4-6-review.md" },
];

const CRITICAL_ARTIFACT_NAMES = ["passto-research.md", "passto-integration-notes.md"];

// ── Artifact Scanning ───────────────────────────────────────────────

function scanExistingArtifacts(planningDir: string): ArtifactStatus[] {
  const results: ArtifactStatus[] = [];

  for (const def of ARTIFACT_SCAN_LIST) {
    const fullPath = path.join(planningDir, def.file);
    const content = readTextFile(fullPath);
    results.push({
      name: def.name,
      path: fullPath,
      exists: content !== null,
      size: content !== null ? content.length : null,
    });
  }

  return results;
}

// ── Unresolved Item Detection ───────────────────────────────────────

function detectUnresolvedItems(
  artifacts: ArtifactStatus[],
  integrationContent: string | null,
): string[] {
  const unresolved: string[] = [];

  // Check for missing critical artifacts
  const missingCritical = artifacts.filter(
    (a) =>
      !a.exists &&
      CRITICAL_ARTIFACT_NAMES.includes(a.name),
  );

  for (const m of missingCritical) {
    unresolved.push(`Missing critical artifact: ${m.name} (${m.path})`);
  }

  // Check integration notes for unresolved findings
  if (integrationContent) {
    const unresolvedSectionIdx = integrationContent.indexOf("## Unresolved Findings");
    if (unresolvedSectionIdx !== -1) {
      // Extract bullet points from unresolved section
      const sectionEnd = integrationContent.indexOf("\n## ", unresolvedSectionIdx + 1);
      const sectionContent = sectionEnd !== -1
        ? integrationContent.substring(unresolvedSectionIdx, sectionEnd)
        : integrationContent.substring(unresolvedSectionIdx);

      const bulletRegex = /^- (.+)$/gm;
      let match;
      while ((match = bulletRegex.exec(sectionContent)) !== null) {
        const item = match[1].trim();
        // Skip the "no unresolved" placeholder
        if (item && !item.startsWith("*No")) {
          unresolved.push(item);
        }
      }
    }
  }

  // Check review files for error sections
  const reviewArtifacts = artifacts.filter((a) => a.name.includes("review") && a.exists);
  for (const review of reviewArtifacts) {
    const content = readTextFile(review.path);
    if (!content) continue;

    const errorSectionIdx = content.indexOf("## Review Errors");
    if (errorSectionIdx !== -1) {
      unresolved.push(`${review.name} has review errors requiring attention`);
    }
  }

  return unresolved;
}

// ── Readiness Assessment ────────────────────────────────────────────

function assessReadiness(
  artifacts: ArtifactStatus[],
  unresolved: string[],
): boolean {
  // Must have at least integration notes (Step 10 output)
  const hasIntegration = artifacts.find(
    (a) => a.name === "passto-integration-notes.md",
  )?.exists;

  // If integration notes don't exist, we can still proceed if we have
  // at least some artifacts — the review gate will note the gap
  if (!hasIntegration) {
    // Check if we have any meaningful artifacts at all
    const hasAnySubstantive = artifacts.some(
      (a) => a.exists && a.size !== null && a.size > 50,
    );
    return hasAnySubstantive;
  }

  // If integration exists but has unresolved items, still "ready" but
  // the summary will flag them
  return true;
}

// ── Output Generation ───────────────────────────────────────────────

function buildReviewGateMarkdown(
  config: ReviewGateConfig,
  artifacts: ArtifactStatus[],
  unresolved: string[],
  reviewGateReady: boolean,
): string {
  const lines: string[] = [];

  lines.push("# Passto Review Gate");
  lines.push("");
  lines.push(`Generated by passto-planner Step 11 · Run: ${config.runId}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Gate Status
  lines.push("## Gate Status");
  lines.push("");
  lines.push(`- Ready for review: ${reviewGateReady ? "Yes" : "No"}`);
  lines.push(`- Goal: ${config.goal}`);
  if (config.target) lines.push(`- Target: ${config.target}`);
  lines.push(`- Artifacts scanned: ${artifacts.length}`);
  lines.push(`- Artifacts found: ${artifacts.filter((a) => a.exists).length}`);
  lines.push(`- Unresolved items: ${unresolved.length}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Available Artifacts
  lines.push("## Available Artifacts");
  lines.push("");
  lines.push("| Artifact | Status | Size |");
  lines.push("|----------|--------|------|");
  for (const a of artifacts) {
    const status = a.exists ? "✅ Present" : "❌ Missing";
    const size = a.size !== null ? `${a.size} bytes` : "N/A";
    lines.push(`| ${a.name} | ${status} | ${size} |`);
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  // Unresolved Items
  lines.push("## Unresolved Items");
  lines.push("");
  if (unresolved.length) {
    for (const item of unresolved) {
      lines.push(`- ${item}`);
    }
  } else {
    lines.push("*No unresolved items detected.*");
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  // Recommendation
  lines.push("## Recommendation");
  lines.push("");
  if (reviewGateReady) {
    lines.push("Proceed to Step 12 (final plan generation).");
    if (unresolved.length) {
      lines.push(`Note: ${unresolved.length} unresolved item(s) are tracked above but do not block plan generation.`);
    }
  } else {
    lines.push("Insufficient artifacts for review gate. Consider running prior steps first:");
    lines.push("- Step 4: Research (`passto-research.md`)");
    lines.push("- Step 9: Review (review files)");
    lines.push("- Step 10: Integration (`passto-integration-notes.md`)");
  }
  lines.push("");

  return lines.join("\n");
}

// ── Main Entry ─────────────────────────────────────────────────────

export async function runStep11ReviewGate(config: ReviewGateConfig): Promise<ReviewGateArtifact> {
  // Scan existing artifacts
  const artifacts = scanExistingArtifacts(config.planningDir);

  // Read integration notes for unresolved item extraction
  const integrationPath = path.join(config.planningDir, "passto-integration-notes.md");
  const integrationContent = readTextFile(integrationPath);

  // Detect unresolved items
  const unresolved = detectUnresolvedItems(artifacts, integrationContent);

  // Assess readiness
  const reviewGateReady = assessReadiness(artifacts, unresolved);

  // Build and write review gate artifact
  const markdown = buildReviewGateMarkdown(config, artifacts, unresolved, reviewGateReady);
  const filePath = path.join(config.planningDir, "review-gate-summary.md");
  writeTextFile(filePath, markdown);

  const summary = reviewGateReady
    ? `Review gate passed: ${artifacts.filter((a) => a.exists).length}/${artifacts.length} artifacts present, ${unresolved.length} unresolved.`
    : `Review gate blocked: insufficient artifacts (${artifacts.filter((a) => a.exists).length}/${artifacts.length} present).`;

  return {
    availableArtifacts: artifacts,
    unresolvedItems: unresolved,
    reviewGateReady,
    summary,
    filePath,
  };
}
