// Step 9: Minimal review module for passto-planner.
// Constructs review tasks, executes them via nested execution,
// aggregates results, and writes review files to <planningDir>/reviews/.

import type {
  NestedTaskSpec,
  NestedExecutionResult,
} from "./nested-execution.ts";
import { runNestedPlannerExecution } from "./nested-execution.ts";
import { writeTextFile, readTextFile } from "./file-io.ts";
import * as path from "node:path";

// ── Public Types ────────────────────────────────────────────────────

export interface ReviewConfig {
  runId: string;
  planningDir: string;
  goal: string;
  target?: string;
  cwd?: string;
}

export interface ReviewArtifact {
  reviewerId: string;
  filePath: string;
  content: string;
}

export interface ReviewOutput {
  artifacts: ReviewArtifact[];
  taskCount: number;
  succeeded: number;
  failed: number;
  summary: string;
}

// ── Reviewer Definitions ────────────────────────────────────────────

interface ReviewerDef {
  id: string;
  name: string;
  kind: "review-plan" | "review-spec";
  focus: string;
}

const REVIEWERS: ReviewerDef[] = [
  {
    id: "gpt-5.4",
    name: "GPT-5.4",
    kind: "review-plan",
    focus: "plan structure, input chain, constraint fidelity, artifact completeness",
  },
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    kind: "review-spec",
    focus: "spec synthesis, requirements traceability, edge case coverage",
  },
];

// ── Input Gathering ─────────────────────────────────────────────────

function gatherReviewContext(planningDir: string): {
  prePlan: string | null;
  spec: string | null;
  analysis: string | null;
} {
  return {
    prePlan: readTextFile(path.join(planningDir, "pre-plan.md")),
    spec: readTextFile(path.join(planningDir, "passto-spec.md")),
    analysis: readTextFile(path.join(planningDir, "analysis.md")),
  };
}

// ── Task Construction ──────────────────────────────────────────────

function buildReviewTasks(config: ReviewConfig): NestedTaskSpec[] {
  const context = gatherReviewContext(config.planningDir);
  const tasks: NestedTaskSpec[] = [];

  for (const reviewer of REVIEWERS) {
    // Build a context summary from available artifacts
    const contextParts: string[] = [];
    if (context.prePlan) contextParts.push(`Pre-plan exists (${context.prePlan.length} chars)`);
    if (context.spec) contextParts.push(`Spec exists (${context.spec.length} chars)`);
    if (context.analysis) contextParts.push(`Analysis exists (${context.analysis.length} chars)`);
    const contextSummary = contextParts.length
      ? contextParts.join("; ")
      : "No prior artifacts available; review based on goal and target only.";

    tasks.push({
      id: `review-${reviewer.id}-01`,
      kind: reviewer.kind,
      title: `${reviewer.name} Review: ${reviewer.focus}`,
      prompt:
        `Perform a structured review of the planning output, focusing on: ${reviewer.focus}. ` +
        `Review context: ${contextSummary}. ` +
        `Goal: ${config.goal}. ` +
        (config.target ? `Target: ${config.target}. ` : "") +
        "Do NOT write any files. Return structured findings only.",
      metadata: {
        reviewer: reviewer.name,
        reviewTarget: reviewer.kind === "review-plan" ? "plan" : "spec",
        reviewerId: reviewer.id,
        contextSummary,
      },
    });
  }

  return tasks;
}

// ── Output Formatting ──────────────────────────────────────────────

function formatReviewMarkdown(
  reviewerId: string,
  reviewerName: string,
  executionResult: NestedExecutionResult,
  config: ReviewConfig,
): string {
  const lines: string[] = [];

  lines.push(`# ${reviewerName} Review`);
  lines.push("");
  lines.push(`Generated by passto-planner Step 9 · Run: ${config.runId}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Review Scope
  lines.push("## Review Scope");
  lines.push("");
  lines.push(`- Goal: ${config.goal}`);
  if (config.target) lines.push(`- Target: ${config.target}`);
  lines.push(`- Reviewer: ${reviewerName}`);
  lines.push(`- Focus: ${REVIEWERS.find(r => r.id === reviewerId)?.focus ?? "general review"}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Findings from task results
  const reviewerTasks = (executionResult.taskResults ?? []).filter(
    (r) => r.metadata?.reviewerId === reviewerId,
  );

  if (reviewerTasks.length) {
    for (const task of reviewerTasks) {
      lines.push(task.outputText);
      lines.push("");
    }
  } else {
    lines.push("*No review results available for this reviewer.*");
    lines.push("");
  }

  lines.push("---");
  lines.push("");

  // Summary
  const failedTasks = reviewerTasks.filter((r) => r.status === "failed");
  if (failedTasks.length) {
    lines.push("## Review Errors");
    lines.push("");
    for (const task of failedTasks) {
      lines.push(`- **${task.summary}**: ${task.failureReason ?? "unknown error"}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

// ── Main Entry ─────────────────────────────────────────────────────

export async function runStep9Review(config: ReviewConfig): Promise<ReviewOutput> {
  const tasks = buildReviewTasks(config);

  const executionResult = await runNestedPlannerExecution({
    runId: config.runId,
    goal: config.goal,
    phase: "review",
    strategy: "subagent",
    tasks,
    maxConcurrency: 1,
  });

  const taskResults = executionResult.taskResults ?? [];
  const succeeded = taskResults.filter((r) => r.status === "success").length;
  const failed = taskResults.filter((r) => r.status === "failed").length;

  // Write individual review files
  const artifacts: ReviewArtifact[] = [];

  for (const reviewer of REVIEWERS) {
    const markdown = formatReviewMarkdown(reviewer.id, reviewer.name, executionResult, config);
    const reviewFilePath = path.join(config.planningDir, "reviews", `${reviewer.id}-review.md`);
    writeTextFile(reviewFilePath, markdown);

    artifacts.push({
      reviewerId: reviewer.id,
      filePath: reviewFilePath,
      content: markdown,
    });
  }

  return {
    artifacts,
    taskCount: tasks.length,
    succeeded,
    failed,
    summary: executionResult.summary,
  };
}
