import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';

import { buildGeneratorCharterPrompt } from '../grc-prompts.ts';
import { projectGeneratorCharterPrompt } from '../grc-generator-contract.ts';

const CONTRACT_PATH = path.resolve(import.meta.dirname, '../references/generator-contract.md');

test('buildGeneratorCharterPrompt explains dynamic-layer semantics without repeating Constitution', async () => {
  const prompt = buildGeneratorCharterPrompt();
  const contract = await fs.readFile(CONTRACT_PATH, 'utf-8');

  assert.match(prompt, /GoalState：当前目标链锚点与焦点真相源/);
  assert.match(prompt, /SummaryCache：当前上下文中的近期历史补充层/);
  assert.match(prompt, /Reflector Advice：post-round 纠偏建议/);
  assert.match(prompt, /Principles：分为两层：`manual \+ promoted` 的人工宪法原则，以及其余跨多轮、多任务复现过的历史经验启发/);
  assert.match(prompt, /人工宪法原则优先于普通历史经验层/);
  assert.match(prompt, /LLM-primary context runtime/);
  assert.match(prompt, /不是 script-driven agent state machine/);
  assert.match(prompt, /辅助设施/);
  assert.match(prompt, /不替代 LLM 做语义目标裁决/);
  assert.match(prompt, /找不到状态时必须暴露 unresolved_context_state warning，不得静默创建 root goal/);
  assert.match(prompt, /Object sidecars.*软性动态信息参数层/);
  assert.match(prompt, /不提供最终语义裁决/);
  assert.match(prompt, /before-agent-start-injection\.ts 负责拼装 LLM runtime input/);
  assert.match(prompt, /candidate、hint、evidence、warning/);
  assert.match(prompt, /当前阶段由 LLM/);
  assert.match(prompt, /phaseCandidate/);
  assert.match(prompt, /不是自动进入 goal_materialization/);
  assert.match(prompt, /用户最新输入为核心/);
  assert.match(prompt, /projection API 只负责校验、持久化与返回 warning/);
  assert.match(prompt, /xNodeModel 是可恢复执行框架，不是脚本硬状态机/);
  assert.match(prompt, /method packet.*方法论函数引用/);
  assert.match(prompt, /不命令 LLM 下一步必须执行哪个方法/);
  assert.match(prompt, /subagent.*辅助执行设施/);
  assert.match(prompt, /主 LLM 必须验证 subagent 输出/);
  assert.match(prompt, /父目标回归是 LLM-owned reasoning/);
  assert.doesNotMatch(prompt, /script.*decides.*phase/i);
  assert.doesNotMatch(prompt, /automatically create.*root goal/i);
  assert.doesNotMatch(prompt, /must execute.*recommendedMethod/i);
  assert.match(prompt, /理清真正的需求/);
  assert.match(prompt, /考虑是否有替代方案/);
  assert.match(prompt, /关注假设是否成立/);
  assert.match(prompt, /更上层目标链/);
  assert.match(prompt, /最近若干个 agent-round 的原始对话/);
  assert.match(prompt, /最能推进结果的单一动作/);
  assert.match(prompt, /显式说明依据/);
  assert.match(prompt, /`Why`：先判断当前目标服务于哪个更上层目标/);
  assert.match(prompt, /`What`：先收敛这一轮真正要产出的对象与完成定义/);
  assert.match(prompt, /`Flow`：先用当前用户消息与上下文窗口中的最近执行现场判断下一步/);
  assert.match(prompt, /`Structure`：先识别当前依赖的 truth source、实现层级/);
  assert.match(prompt, /`Runtime Proof`：先确认当前判断是否已被源码、工具结果、运行时状态或其他现实证据支撑/);
  assert.match(prompt, /先 `Why`，再 `What`，再 `Flow`，再 `Structure`/);
  assert.match(prompt, /userGoal\.executionState=planning 且当前 xNode 的 why \/ what 未闭合/);
  assert.match(prompt, /idea-refine 方法来提升目标确定性/);
  assert.match(prompt, /problem statement、recommended direction、key assumptions、MVP scope、not doing list、open questions/);
  assert.match(prompt, /不要把所有 planning 阶段都拉回 idea-refine/);
  assert.match(prompt, /direct-answer gate/);
  assert.match(prompt, /简单高确定性请求/);
  assert.match(prompt, /不展开递归 xNodeModel/);
  assert.match(prompt, /plan-certainty-improvement/);
  assert.match(prompt, /ContextParameterRequest/);
  assert.match(prompt, /CertaintyAssessment、XNodeModelPatch、RuntimeProofRecord/);
  assert.match(prompt, /`patch_xnode` 写入 why \/ what \/ flow \/ structure \/ runtimeProof facet/);
  assert.match(prompt, /ProposedXNodeModelPatch/);
  assert.match(prompt, /待持久化/);
  assert.match(prompt, /并行调用 subagent \/ provider/);
  assert.match(prompt, /为什么做这一步/);
  assert.match(prompt, /当前缺少哪些 facet 或参数/);
  assert.match(prompt, /我获取了什么信息/);
  assert.match(prompt, /来源类型、获取目的与关键信息摘要/);
  assert.match(prompt, /确定性变化/);
  assert.match(prompt, /why \/ what \/ flow \/ structure \/ runtimeProof 汇报 certainty delta/);
  assert.match(prompt, /写入对象与状态/);
  assert.match(prompt, /CertaintyAssessment、XNodeModelPatch、RuntimeProofRecord、ImplementationPlan 或 CertaintyImprovementStatus/);
  assert.match(prompt, /退出判断.*下一步/);
  assert.match(prompt, /不得暴露完整思维链/);

  assert.match(contract, /## Generator Charter/);
  assert.match(contract, /## Dynamic Layer Semantics/);
  assert.match(prompt, /优先判断当前用户消息是在继续、补充、纠偏，还是切换目标/);
  assert.match(prompt, /不得覆盖当前目标与现实证据/);
  assert.match(prompt, /判断当前用户消息是在继续已有 active userGoal，还是引入了新的独立 userGoal/);
  assert.match(prompt, /why（这条消息的动机服务于哪个已有目标/);
  assert.match(prompt, /applyUserGoalProjection/);
  assert.match(prompt, /reviewState/);
  assert.match(prompt, /currentFocusXNode/);
  assert.match(prompt, /local complete.*parent complete/);
  assert.match(prompt, /bounded atomic task/);

  assert.doesNotMatch(prompt, /修改文件后必须复核/);
  assert.doesNotMatch(prompt, /工具结果优先于内部知识/);
  assert.doesNotMatch(prompt, /当前轮事实/);
});

test('buildGeneratorCharterPrompt stays projection-first even when legacy draft flag is enabled', async () => {
  const prompt = buildGeneratorCharterPrompt({ draftGoalEnabled: true });

  assert.match(prompt, /applyUserGoalProjection/);
  assert.match(prompt, /userGoalTree/);
  assert.match(prompt, /xNodeModel.*执行框架|skeleton/);
  assert.match(prompt, /reviewState/);
  assert.doesNotMatch(prompt, /Draft Goal Runtime 协议/);
  assert.doesNotMatch(prompt, /draftGoalOp/);
});

test('projectGeneratorCharterPrompt falls back to built-in charter when contract is missing', () => {
  const prompt = projectGeneratorCharterPrompt(null);

  assert.match(prompt, /PasstoContext Generator Charter/);
  assert.match(prompt, /LLM-primary context runtime/);
  assert.match(prompt, /不是 script-driven agent state machine/);
  assert.match(prompt, /辅助设施/);
  assert.match(prompt, /不替代 LLM 做语义目标裁决/);
  assert.match(prompt, /unresolved_context_state warning，不得静默创建 root goal/);
  assert.match(prompt, /Object sidecars.*软性动态信息参数层/);
  assert.match(prompt, /before-agent-start-injection\.ts 负责拼装 LLM runtime input/);
  assert.match(prompt, /phaseCandidate/);
  assert.match(prompt, /method packet.*方法论函数引用/);
  assert.match(prompt, /subagent.*辅助执行设施/);
  assert.match(prompt, /父目标回归是 LLM-owned reasoning/);
  assert.match(prompt, /更上层目标链/);
  assert.match(prompt, /最近若干个 agent-round 的原始对话/);
  assert.match(prompt, /GoalState 是当前目标链锚点/);
  assert.match(prompt, /SummaryCache 是当前上下文中的近期历史补充层/);
  assert.match(prompt, /Reflector advice 是纠偏建议/);
  assert.match(prompt, /principles 分两层：manual \+ promoted 为人工宪法原则，其余为历史经验启发/);
  assert.match(prompt, /人工宪法原则优先于普通历史经验层/);
  assert.match(prompt, /理清真正的需求/);
  assert.match(prompt, /考虑替代方案/);
  assert.match(prompt, /检查关键假设/);
  assert.match(prompt, /Why：先判断当前目标服务于哪个更上层目标/);
  assert.match(prompt, /What：先收敛这一轮真正要产出的对象与完成定义/);
  assert.match(prompt, /Flow：先用当前用户消息与上下文窗口中的最近执行现场判断下一步/);
  assert.match(prompt, /Structure：先识别当前依赖的 truth source、实现层级/);
  assert.match(prompt, /Runtime Proof：先确认当前判断是否已被源码、工具结果、运行时状态或其他现实证据支撑/);
  assert.match(prompt, /处理用户消息前，先判断它是在继续已有 active userGoal 还是引入新目标/);
  assert.match(prompt, /applyUserGoalProjection/);
  assert.match(prompt, /local complete.*parent complete/);
  assert.match(prompt, /bounded atomic task/);
  assert.match(prompt, /idea-refine 方法来提升目标确定性/);
  assert.match(prompt, /problem statement、recommended direction、key assumptions、MVP scope、not doing list、open questions/);
  assert.match(prompt, /direct-answer gate/);
  assert.match(prompt, /简单高确定性请求/);
  assert.match(prompt, /不展开递归 xNodeModel/);
  assert.match(prompt, /plan-certainty-improvement/);
  assert.match(prompt, /ContextParameterRequest/);
  assert.match(prompt, /ProposedXNodeModelPatch/);
  assert.match(prompt, /并行调用 subagent \/ provider/);
  assert.match(prompt, /为什么做这一步/);
  assert.match(prompt, /我获取了什么信息/);
  assert.match(prompt, /确定性变化/);
  assert.match(prompt, /写入对象与状态/);
  assert.match(prompt, /不得暴露完整思维链/);
  assert.doesNotMatch(prompt, /修改文件后必须复核/);
  assert.doesNotMatch(prompt, /工具结果优先于内部知识/);
});
