import {
  createBuilderArtifactRef,
  createBuilderSummaryArtifact,
  writeBuilderWorkspaceNote,
} from "./artifacts.ts";
import type { BuilderRunState } from "./state.ts";
import { runRalphLoopEngine } from "../loop-engine/ralph-loop-engine.ts";
import { buildExecutorBridgeRequest } from "../executor-bridge/passto-executor-bridge.ts";
import type { BuilderWorkflowServices } from "./test-seams.ts";

export type BuilderWorkflowSnapshotListener = (state: BuilderRunState) => void;

export async function runBuilderWorkflow(
  state: BuilderRunState,
  onSnapshot?: BuilderWorkflowSnapshotListener,
  services: BuilderWorkflowServices = {},
): Promise<BuilderRunState> {
  state.phase = "prepare";
  state.status = "preparing";
  state.currentAction = "Preparing builder execution context";
  state.summary = "Validated builder input and preparing local plan";
  onSnapshot?.(state);

  state.phase = "local_plan";
  state.currentAction = "Generating local execution todo list";
  state.todoList = state.input.todolist.length > 0
    ? [...state.input.todolist]
    : [
        `Review task: ${state.input.goal}`,
        ...state.input.expectedOutputs.map((output) => `Produce output: ${output}`),
      ];
  state.summary = "Local execution plan prepared";
  onSnapshot?.(state);

  state.phase = "execute";
  state.status = "executing";
  state.currentAction = "Executing builder task through Ralph loop engine";
  const bridgeRequest = services.bridgeRequestFactory
    ? services.bridgeRequestFactory(state)
    : buildExecutorBridgeRequest(state.input);
  state.artifacts.push(
    createBuilderArtifactRef({
      type: "executor-bridge-request",
      runId: bridgeRequest.runId,
      summary: `Prepared executor bridge request ${bridgeRequest.runId}`,
      metadata: bridgeRequest.metadata,
    }),
  );
  onSnapshot?.(state);
  const loop = await runRalphLoopEngine(state.input);
  state.summary = loop.result.summary;
  state.completedItems.push("execute");
  state.artifacts.push(
    createBuilderArtifactRef({
      type: "loop-engine-summary",
      runId: bridgeRequest.runId,
      summary: loop.result.summary,
      metadata: bridgeRequest.metadata,
    }),
  );
  const workspaceNote = await (services.workspaceNoteWriter ?? writeBuilderWorkspaceNote)({
    cwd: state.input.cwd,
    title: state.input.goal,
    lines: [
      `Execution prompt: ${state.input.executionPrompt}`,
      `Executor run id: ${bridgeRequest.runId}`,
      `Loop summary: ${loop.result.summary}`,
      `Expected outputs: ${state.input.expectedOutputs.join(", ") || "(none specified)"}`,
      "This note was generated by the early passto-builder vertical slice.",
    ],
  });
  state.artifacts.push({
    ...workspaceNote,
    runId: bridgeRequest.runId,
    metadata: {
      ...(workspaceNote.metadata ?? {}),
      ...bridgeRequest.metadata,
    },
  });
  state.completedItems.push("workspace-note");
  onSnapshot?.(state);

  state.phase = "verify";
  state.status = "verifying";
  state.currentAction = "Verifying execution outputs";
  state.summary = workspaceNote.path
    ? `Verification initialized after writing ${workspaceNote.path}`
    : "Verification phase initialized";
  state.artifacts.push(
    createBuilderArtifactRef({
      type: "verification-summary",
      runId: bridgeRequest.runId,
      summary: workspaceNote.path
        ? `Verified workspace note exists at ${workspaceNote.path}`
        : "Verification completed without workspace note path",
      metadata: {
        ...bridgeRequest.metadata,
        verifiedArtifactType: "workspace-note",
        verifiedPath: workspaceNote.path,
      },
    }),
  );
  state.completedItems.push("verify");
  onSnapshot?.(state);

  state.phase = "summarize";
  state.status = "summarizing";
  state.currentAction = "Summarizing builder results";
  state.summary = "Builder workflow completed first executor-backed file-output path with verification summary";
  state.artifacts.push({
    ...createBuilderSummaryArtifact(state.summary),
    runId: bridgeRequest.runId,
    metadata: bridgeRequest.metadata,
  });
  onSnapshot?.(state);

  state.status = "completed";
  return state;
}
